In [ ]:
# Session 2 - quick sanity check on the target variable G3
import pandas as pd
import zipfile
import requests
from io import BytesIO

# UCI Student Performance dataset ZIP file

# Session 2 - quick sanity check on the target variable G3

# Define the direct path to your CSV file in Google Drive
file_path = "/content/drive/MyDrive/GSSRP_Project/student-mat.csv"

# Load the CSV directly (specifying the semicolon separator used by UCI datasets)
df = pd.read_csv(file_path, sep=';')

# Quick sanity checks
print("Rows, columns:", df.shape)
print(df[['G1', 'G2', 'G3']].describe())

df['at_risk'] = (df['G3'] < 10).astype(int)
print(df['at_risk'].value_counts())

Rows, columns: (395, 33)
               G1          G2          G3
count  395.000000  395.000000  395.000000
mean    10.908861   10.713924   10.415190
std      3.319195    3.761505    4.581443
min      3.000000    0.000000    0.000000
25%      8.000000    9.000000    8.000000
50%     11.000000   11.000000   11.000000
75%     13.000000   13.000000   14.000000
max     19.000000   19.000000   20.000000
at_risk
0    265
1    130
Name: count, dtype: int64

Scientific research paper:  **Systematic Literature Review of Student’ Performance
Prediction Using Machine Learning Techniques**

Researchers looked at a bunch of EDM studies from 2009 to 2021
Using a bunch of metrics for the data that was used for all of the studies the researchers decided that machine learning does work for analyzing mass data and predicting at-risk students. So education and EDM in general are benefitting a lot from ML.

--------------

Supervised learning is where data is labeled which makes the model predict a specific variable. Classification and regression are the fundamental examples of supervised learning

Unsupervised learning is where the data does not have any labels so we force the model to work blindly which allows us to see how the model truly works in terms of its patterns and structure.
K-means clustering and image compression.


----------------

Libraries: pandas, polars, os, regex, numpy, pytorch, matplotlib

Functions eliminate redundancy in programs, they take an input and produce an output

A dataframe is a versatile structure in Python for holding data that can be modified.

In [ ]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,at_risk
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,1
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,1
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,0
5,GP,M,16,U,LE3,T,4,3,services,other,...,4,2,1,2,5,10,15,15,15,0
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,1,1,3,0,12,12,11,0
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,1,4,1,1,1,6,6,5,6,1
8,GP,M,15,U,LE3,A,3,2,services,other,...,2,2,1,1,1,0,16,18,19,0
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,1,1,1,5,0,14,15,15,0

In [ ]:
summary = pd.DataFrame({
"dtype": df.dtypes.astype(str),
"n_unique": df.nunique(),
"n_missing": df.isna().sum(),
})

print(summary)

             dtype  n_unique  n_missing
school      object         2          0
sex         object         2          0
age          int64         8          0
address     object         2          0
famsize     object         2          0
Pstatus     object         2          0
Medu         int64         5          0
Fedu         int64         5          0
Mjob        object         5          0
Fjob        object         5          0
reason      object         4          0
guardian    object         3          0
traveltime   int64         4          0
studytime    int64         4          0
failures     int64         4          0
schoolsup   object         2          0
famsup      object         2          0
paid        object         2          0
activities  object         2          0
nursery     object         2          0
higher      object         2          0
internet    object         2          0
romantic    object         2          0
famrel       int64         5          0
freetime     int64         5          0
goout        int64         5          0
Dalc         int64         5          0
Walc         int64         5          0
health       int64         5          0
absences     int64        34          0
G1           int64        17          0
G2           int64        17          0
G3           int64        18          0
at_risk      int64         2          0

In [ ]:
summary = pd.DataFrame({
"dtype": df.dtypes.astype(str),
"n_unique": df.nunique(),
"n_missing": df.isna().sum(),
})

display(summary)

             dtype  n_unique  n_missing
school      object         2          0
sex         object         2          0
age          int64         8          0
address     object         2          0
famsize     object         2          0
Pstatus     object         2          0
Medu         int64         5          0
Fedu         int64         5          0
Mjob        object         5          0
Fjob        object         5          0
reason      object         4          0
guardian    object         3          0
traveltime   int64         4          0
studytime    int64         4          0
failures     int64         4          0
schoolsup   object         2          0
famsup      object         2          0
paid        object         2          0
activities  object         2          0
nursery     object         2          0
higher      object         2          0
internet    object         2          0
romantic    object         2          0
famrel       int64         5          0
freetime     int64         5          0
goout        int64         5          0
Dalc         int64         5          0
Walc         int64         5          0
health       int64         5          0
absences     int64        34          0
G1           int64        17          0
G2           int64        17          0
G3           int64        18          0
at_risk      int64         2          0

In [ ]:
summary = pd.DataFrame({
"variable": df.columns,
"dtype": df.dtypes.astype(str).values,
"n_unique": df.nunique().values,
"n_missing": df.isna().sum().values,
})
display(summary)

      variable   dtype  n_unique  n_missing
0       school  object         2          0
1          sex  object         2          0
2          age   int64         8          0
3      address  object         2          0
4      famsize  object         2          0
5      Pstatus  object         2          0
6         Medu   int64         5          0
7         Fedu   int64         5          0
8         Mjob  object         5          0
9         Fjob  object         5          0
10      reason  object         4          0
11    guardian  object         3          0
12  traveltime   int64         4          0
13   studytime   int64         4          0
14    failures   int64         4          0
15   schoolsup  object         2          0
16      famsup  object         2          0
17        paid  object         2          0
18  activities  object         2          0
19     nursery  object         2          0
20      higher  object         2          0
21    internet  object         2          0
22    romantic  object         2          0
23      famrel   int64         5          0
24    freetime   int64         5          0
25       goout   int64         5          0
26        Dalc   int64         5          0
27        Walc   int64         5          0
28      health   int64         5          0
29    absences   int64        34          0
30          G1   int64        17          0
31          G2   int64        17          0
32          G3   int64        18          0
33     at_risk   int64         2          0

In [ ]:
print(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3', 'at_risk'],
      dtype='object')

In [ ]:
df["passed"] = (df["G3"] >= 10).astype(int)
print(df["passed"].value_counts())
print("Regression target: G3")
print("Classification target: passed (1 if G3>=10 else 0)")

passed
1    265
0    130
Name: count, dtype: int64
Regression target: G3
Classification target: passed (1 if G3>=10 else 0)

In [ ]:
df[["G3", "passed"]].head()

   G3  passed
0   6       0
1   6       0
2  10       1
3  15       1
4  10       1

# Target Definition Note
## Regression Target
The regression target is `G3`, which represents the student's final grade. This
target will be used when the model predicts a numeric final grade.
## Classification Target
The classification target is `passed`. This target converts the final grade into a
binary outcome.
The classification rule is:
passed = 1 if G3 >= 10
passed = 0 if G3 < 10
This means that students with final grades of 10 or higher are labeled as passing,
while students with final grades below 10 are labeled as not passing.
## Chosen Threshold
The chosen threshold is `G3 >= 10` for passing. Students with `G3 < 10` are
considered at risk or not passing.
## Limitation
One limitation of this threshold is that it creates a hard cutoff. For example, a
student with `G3 = 9` is labeled as not passing, while a student with `G3 = 10` is
labeled as passing. However, these two students may have very similar academic
performance.
## Final Decision
For the first version of the project, we will keep the `G3 >= 10` threshold because
it is simple, clear, and easy to explain. However, we will document its limitation
and may compare it with other thresholds, such as `G3 < 12`, in a later version of
the project.

In [ ]:
print(df.shape)
print(df.info())
print(df.describe(include="all").T)

(395, 35)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
 33  at_risk     395 non-null    int64
 34  passed      395 non-null    int64
dtypes: int64(18), object(17)
memory usage: 108.1+ KB
None
            count unique     top freq       mean       std   min   25%   50%  \
school        395      2      GP  349        NaN       NaN   NaN   NaN   NaN
sex           395      2       F  208        NaN       NaN   NaN   NaN   NaN
age         395.0    NaN     NaN  NaN  16.696203  1.276043  15.0  16.0  17.0
address       395      2       U  307        NaN       NaN   NaN   NaN   NaN
famsize       395      2     GT3  281        NaN       NaN   NaN   NaN   NaN
Pstatus       395      2       T  354        NaN       NaN   NaN   NaN   NaN
Medu        395.0    NaN     NaN  NaN   2.749367  1.094735   0.0   2.0   3.0
Fedu        395.0    NaN     NaN  NaN   2.521519  1.088201   0.0   2.0   2.0
Mjob          395      5   other  141        NaN       NaN   NaN   NaN   NaN
Fjob          395      5   other  217        NaN       NaN   NaN   NaN   NaN
reason        395      4  course  145        NaN       NaN   NaN   NaN   NaN
guardian      395      3  mother  273        NaN       NaN   NaN   NaN   NaN
traveltime  395.0    NaN     NaN  NaN   1.448101  0.697505   1.0   1.0   1.0
studytime   395.0    NaN     NaN  NaN   2.035443   0.83924   1.0   1.0   2.0
failures    395.0    NaN     NaN  NaN   0.334177  0.743651   0.0   0.0   0.0
schoolsup     395      2      no  344        NaN       NaN   NaN   NaN   NaN
famsup        395      2     yes  242        NaN       NaN   NaN   NaN   NaN
paid          395      2      no  214        NaN       NaN   NaN   NaN   NaN
activities    395      2     yes  201        NaN       NaN   NaN   NaN   NaN
nursery       395      2     yes  314        NaN       NaN   NaN   NaN   NaN
higher        395      2     yes  375        NaN       NaN   NaN   NaN   NaN
internet      395      2     yes  329        NaN       NaN   NaN   NaN   NaN
romantic      395      2      no  263        NaN       NaN   NaN   NaN   NaN
famrel      395.0    NaN     NaN  NaN   3.944304  0.896659   1.0   4.0   4.0
freetime    395.0    NaN     NaN  NaN   3.235443  0.998862   1.0   3.0   3.0
goout       395.0    NaN     NaN  NaN   3.108861  1.113278   1.0   2.0   3.0
Dalc        395.0    NaN     NaN  NaN   1.481013  0.890741   1.0   1.0   1.0
Walc        395.0    NaN     NaN  NaN   2.291139  1.287897   1.0   1.0   2.0
health      395.0    NaN     NaN  NaN    3.55443  1.390303   1.0   3.0   4.0
absences    395.0    NaN     NaN  NaN   5.708861  8.003096   0.0   0.0   4.0
G1          395.0    NaN     NaN  NaN  10.908861  3.319195   3.0   8.0  11.0
G2          395.0    NaN     NaN  NaN  10.713924  3.761505   0.0   9.0  11.0
G3          395.0    NaN     NaN  NaN   10.41519  4.581443   0.0   8.0  11.0
at_risk     395.0    NaN     NaN  NaN   0.329114  0.470487   0.0   0.0   0.0
passed      395.0    NaN     NaN  NaN   0.670886  0.470487   0.0   0.0   1.0

             75%   max
school       NaN   NaN
sex          NaN   NaN
age         18.0  22.0
address      NaN   NaN
famsize      NaN   NaN
Pstatus      NaN   NaN
Medu         4.0   4.0
Fedu         3.0   4.0
Mjob         NaN   NaN
Fjob         NaN   NaN
reason       NaN   NaN
guardian     NaN   NaN
traveltime   2.0   4.0
studytime    2.0   4.0
failures     0.0   3.0
schoolsup    NaN   NaN
famsup       NaN   NaN
paid         NaN   NaN
activities   NaN   NaN
nursery      NaN   NaN
higher       NaN   NaN
internet     NaN   NaN
romantic     NaN   NaN
famrel       5.0   5.0
freetime     4.0   5.0
goout        4.0   5.0
Dalc         2.0   5.0
Walc         3.0   5.0
health       5.0   5.0
absences     8.0  75.0
G1          13.0  19.0
G2          13.0  19.0
G3          14.0  20.0
at_risk      1.0   1.0
passed       1.0   1.0

In [ ]:
print("Dataset shape:")
print(df.shape)
print("\nDataset information:")
df.info()
print("\nSummary statistics:")
display(df.describe(include="all").T)

Dataset shape:
(395, 35)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
 33  at_risk     395 non-null    int64
 34  passed      395 non-null    int64
dtypes: int64(18), object(17)
memory usage: 108.1+ KB

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
school,395,2,GP,349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sex,395,2,F,208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,395.0,NaN,NaN,NaN,16.696203,1.276043,15.0,16.0,17.0,18.0,22.0
address,395,2,U,307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
famsize,395,2,GT3,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pstatus,395,2,T,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Medu,395.0,NaN,NaN,NaN,2.749367,1.094735,0.0,2.0,3.0,4.0,4.0
Fedu,395.0,NaN,NaN,NaN,2.521519,1.088201,0.0,2.0,2.0,3.0,4.0
Mjob,395,5,other,141,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fjob,395,5,other,217,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reason,395,4,course,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
guardian,395,3,mother,273,NaN,NaN,NaN,NaN,NaN,NaN,NaN
traveltime,395.0,NaN,NaN,NaN,1.448101,0.697505,1.0,1.0,1.0,2.0,4.0
studytime,395.0,NaN,NaN,NaN,2.035443,0.83924,1.0,1.0,2.0,2.0,4.0
failures,395.0,NaN,NaN,NaN,0.334177,0.743651,0.0,0.0,0.0,0.0,3.0
schoolsup,395,2,no,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
famsup,395,2,yes,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
paid,395,2,no,214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
activities,395,2,yes,201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nursery,395,2,yes,314,NaN,NaN,NaN,NaN,NaN,NaN,NaN
higher,395,2,yes,375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
internet,395,2,yes,329,NaN,NaN,NaN,NaN,NaN,NaN,NaN
romantic,395,2,no,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
famrel,395.0,NaN,NaN,NaN,3.944304,0.896659,1.0,4.0,4.0,5.0,5.0
freetime,395.0,NaN,NaN,NaN,3.235443,0.998862,1.0,3.0,3.0,4.0,5.0
goout,395.0,NaN,NaN,NaN,3.108861,1.113278,1.0,2.0,3.0,4.0,5.0
Dalc,395.0,NaN,NaN,NaN,1.481013,0.890741,1.0,1.0,1.0,2.0,5.0
Walc,395.0,NaN,NaN,NaN,2.291139,1.287897,1.0,1.0,2.0,3.0,5.0
health,395.0,NaN,NaN,NaN,3.55443,1.390303,1.0,3.0,4.0,5.0,5.0
absences,395.0,NaN,NaN,NaN,5.708861,8.003096,0.0,0.0,4.0,8.0,75.0
G1,395.0,NaN,NaN,NaN,10.908861,3.319195,3.0,8.0,11.0,13.0,19.0
G2,395.0,NaN,NaN,NaN,10.713924,3.761505,0.0,9.0,11.0,13.0,19.0
G3,395.0,NaN,NaN,NaN,10.41519,4.581443,0.0,8.0,11.0,14.0,20.0
at_risk,395.0,NaN,NaN,NaN,0.329114,0.470487,0.0,0.0,0.0,1.0,1.0
passed,395.0,NaN,NaN,NaN,0.670886,0.470487,0.0,0.0,1.0,1.0,1.0

In [ ]:
# The inspection results show the number of rows and columns in the dataset, the data
# type of each variable, and whether any variables contain missing values. The
# summary statistics help us identify the range, average, and distribution of
# numerical variables, as well as the most common values in categorical variables.

# This step is important because machine learning models require clean and well-
# understood data before training.